apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"node-server","creationTimestamp":null,"labels":{"app":"node-server"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"node-server"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"node-server"}},"spec":{"containers":[{"name":"docker","image":"245891646863.dkr.ecr.us-east-1.amazonaws.com/docker","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: 2018-12-15T04:34:24Z
  generation: 1
  labels:
    app: node-server
  name: node-server
  namespace: default
  resourceVersion: "2263"
  selfLink: /apis/apps/v1/namespaces/default/deployments/node-server
  uid: b32d0c6c-0022-11e9-a3b5-0eaff92ad114
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-server
    spec:
      containers:
      - image: 245891646863.dkr.ecr.us-east-1.amazonaws.com/docker
        imagePullPolicy: Always
        name: docker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
