apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Service","apiVersion":"v1","metadata":{"name":"node-server","creationTimestamp":null,"labels":{"app":"node-server"}},"spec":{"ports":[{"protocol":"TCP","port":8080,"targetPort":8080}],"selector":{"app":"node-server"},"type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: 2018-12-15T04:35:34Z
  labels:
    app: node-server
  name: node-server
  namespace: default
  resourceVersion: "2362"
  selfLink: /api/v1/namespaces/default/services/node-server
  uid: dcecf016-0022-11e9-a3b5-0eaff92ad114
spec:
  clusterIP: 100.68.237.158
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31282
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
