apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"apprentice-api","creationTimestamp":null,"labels":{"app":"apprentice-api"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"apprentice-api"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"apprentice-api"}},"spec":{"containers":[{"name":"apprentice-api","image":"957687255356.dkr.ecr.us-west-2.amazonaws.com/apprentice-api:latest","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: 2018-12-15T04:34:24Z
  generation: 1
  labels:
    app: apprentice-api
  name: apprentice-api
  namespace: default
  resourceVersion: "2263"
  selfLink: /apis/apps/v1/namespaces/default/deployments/apprentice-api
  uid: b32d0c6c-0022-11e9-a3b5-0eaff92ad114
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apprentice-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apprentice-api
    spec:
      containers:
      - image: 957687255356.dkr.ecr.us-west-2.amazonaws.com/apprentice-api:latest
        imagePullPolicy: Always
        name: apprentice-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
