apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Service","apiVersion":"v1","metadata":{"name":"apprentice-api","creationTimestamp":null,"labels":{"app":"apprentice-api"}},"spec":{"ports":[{"protocol":"TCP","port":8080,"targetPort":8080}],"selector":{"app":"apprentice-api"},"type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: 2018-12-15T04:35:34Z
  labels:
    app: apprentice-api
  name: apprentice-api
  namespace: default
  resourceVersion: "2362"
  selfLink: /api/v1/namespaces/default/services/apprentice-api
  uid: dcecf016-0022-11e9-a3b5-0eaff92ad114
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apprentice-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
